# 01. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations ?

Answer - 

    NumPy, short for Numerical Python, is a fundamental package for scientific computing and data analysis in Python. Here are some key points about its purpose and advantages:

    PURPOSE OF NUMPY >>

    1. Efficient Array Computations:- NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

    2. Foundation for Other Libraries:- It serves as the backbone for many other scientific computing libraries in Python, such as Pandas, Matplotlib, and SciPy.

    ADVANTAGES OF NUMPY >>

    1. Performance:- NumPy is highly optimized for performance. It uses pre-compiled C code, which makes array operations significantly faster than using Python lists.

    2. Memory Efficiency:- NumPy arrays consume less memory compared to Python lists, as they store elements of the same data type, leading to more efficient storage.

    3. Vectorization:- This feature allows us to perform operations on entire arrays without the need for explicit loops, making the code more concise and readable.

    4. Broadcasting:- NumPy can automatically expand the dimensions of arrays to make them compatible for element-wise operations, simplifying the code and reducing the need for complex loops.

    5. Integration with Other Libraries:- NumPy seamlessly integrates with other scientific libraries, enhancing Python’s capabilities for numerical and data analysis tasks.

    ENHANCING PYTHON'S CAPABILITIES >> 

    > Mathematical Functions:- NumPy includes a wide range of mathematical functions for operations like linear algebra, Fourier transforms, and random number generation.

    > Data Handling:- It provides tools for reading and writing array data to and from files, making it easier to handle large datasets.

    > Interoperability:- NumPy arrays can be used as inputs and outputs for other libraries, facilitating smooth data flow in scientific computing workflows.


# 02. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other ?

Answer - 

    Both np.mean() and np.average() functions in NumPy are used to calculate the average of array elements, but they have some differences in functionality and use cases.

    np.mean() >> syntax - np.mean(arr, axis=None)

    Purpose:- Calculates the arithmetic mean (average) of the elements in an array.
    Weights:- Does not support weights; all elements are considered equally.
    Use Case:- Use np.mean() when needed for a simple arithmetic mean without considering any weights.

    np.average() >> syntax - np.average(arr, axis=None, weights=None)

    Purpose:- Calculates the arithmetic mean and can also compute a weighted average if weights are provided.
    Weights:- Supports weights; can pass an array of weights to compute a weighted average.
    Use Case:- Use np.average() when needed to calculate a weighted average, where different elements contribute differently to the mean.

    When to use each >> 

    Use np.mean() > when it is need for a straightforward arithmetic mean and do not need to consider different weights for the elements.

    Use np.average() > when it is need to calculate a weighted average, where some elements have more significance than others.

# 03. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Answer - 

    Reversing a NumPy array can be done using several methods, depending on the axis along which we want to reverse the array. Here are some common methods :

    1. USING np.flip() >> 

    The np.flip() function reverses the order of elements in an array along the specified axis.

    2. USING SLICING >>

    We can also reverse an array using slicing.

    3. USING np.flipud() and np.fliplr() >>

    np.flipud() flips the array in the up/down direction (along the first axis).
    np.fliplr() flips the array in the left/right direction (along the second axis).

In [ ]:
#Example >> using np.flip()

import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)

#output [5 4 3 2 1]

import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr_2d = np.flip(arr_2d, axis=0)  
print(reversed_arr_2d)


# output 
# [[7 8 9]
# [4 5 6]
# [1 2 3]]

#using slicing >>

import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)

#output [5 4 3 2 1]


import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr_2d = arr_2d[::-1, ::-1]  # Reverse both rows and columns
print(reversed_arr_2d)

#output [[9 8 7][6 5 4] [3 2 1]]



#Using np.flipud() and np.fliplr() >> 

import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr_2d = np.flipud(arr_2d)
print(reversed_arr_2d)


# Output [[7 8 9][4 5 6][1 2 3]]

import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr_2d = np.flipud(arr_2d)
print(reversed_arr_2d)

#output [[7 8 9][4 5 6][1 2 3]]

# 4. How can you determine the data type of elements in a NumPy array ? Discuss the importance of data types in memory management and performance.

Answer - 

    To determine the data type of elements in NumPy array, we can use the 'dtype' attribute. This attribute provides information about the data type of the array's elements. 

    Syntax - print(arr.dtype); (arr_float.dtype); (arr_str.dtype)

    Importance of Data Types in Memory Management and Performance >>
    """By carefully selecting data types, we can optimize both the memory footprint and the performance of our NumPy-based applications. """

    * Memory Allocation ->
        Different data types require different amounts of memory. For example, an int32 type requires 4 bytes, while an int64 type requires 8 bytes. Choosing the appropriate data type helps in efficient memory usage.

    * Performance ->
        Operations on smaller data types are generally faster because they require less memory bandwidth and cache usage. For instance, using int32 instead of int64 can improve performance if the range of values fits within 32 bits.

    * Data Integrity -> 
        Using the correct data type it ensures that the data is stored and processed accurately. For example, using a floating-point type for decimal values prevents loss of precision that might occur with integer types.

    * Error Detection -> 
        Data types help in detecting errors during development. For instance, trying to perform arithmetic operations on incompatible types (like adding a string to an integer) will raise errors, helping developers catch bugs early.

    * Storage Efficiency ->
        Efficient data types reduce the amount of storage required. For example, using uint8 for image data (which typically ranges from 0 to 255) is more storage-efficient than using int32.

# 05.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Answer - 

    An 'ndarray' (short for N-dimensional array) is the core data structure in NumPy. It is a multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape, which is a tuple of N non-negative integers that specify the sizes of each dimension.

    Key Features of 'ndarray' >>

    *Homogeneous Data:-
    All elements in an ndarray must be of the same data type, which ensures efficient memory usage and performance1.
    *Multidimensional:-
    ndarray can have any number of dimensions, making it suitable for representing complex data structures like matrices, tensors, and higher-dimensional datasets1.
    *Efficient Memory Layout:-
    ndarray objects are stored in contiguous blocks of memory, which allows for efficient access and manipulation of data1.
    *Broadcasting:-
    NumPy supports broadcasting, which allows arithmetic operations on arrays of different shapes by automatically expanding their dimensions to match each other2.
    *Vectorized Operations:-
    Operations on ndarray are vectorized, meaning they are applied element-wise, which is much faster than using loops in standard Python lists.
    *Indexing and Slicing:-
    ndarray supports advanced indexing and slicing, allowing for efficient data manipulation and retrieval1.
    *Universal Functions (ufuncs):-
    NumPy provides a large number of universal functions that operate element-wise on ndarray, making mathematical operations concise and efficient.

    Differences between ndarray and standard Python lists >>

    * Data Type Homogeneity:-
    ndarray: All elements must be of the same data type.
    Python Lists: Can contain elements of different data types.

    * Performance:-
    ndarray: Operations are faster due to contiguous memory allocation and vectorized operations.
    Python Lists: Slower for numerical computations due to the overhead of dynamic typing and lack of contiguous memory allocation.

    * Memory Efficiency :-
    ndarray: More memory-efficient as it stores elements in a contiguous block of memory.
    Python Lists: Less memory-efficient due to the overhead of storing references to objects.

    * Functionality:-
    ndarray: Provides a wide range of mathematical functions and operations optimized for numerical computations.
    Python Lists: Limited built-in functionality for numerical operations; requires additional libraries for similar capabilities.

    * Dimensionality:-
    ndarray: Supports multiple dimensions (2D, 3D, etc.).
    Python Lists: Primarily one-dimensional, though nested lists can simulate multi-dimensional arrays, but with less efficiency and more complexity.

# 06. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations. 

Answer - 

    NumPy arrays offer significant performance benefits over Python lists, especially for large-scale numerical operations.

    Key Reasons >> 

    * Memory Efficiency >
    Contiguous Memory Allocation:- NumPy arrays are stored in contiguous blocks of memory, which reduces the overhead associated with memory allocation and access. This leads to more efficient use of memory compared to Python lists, which store elements as separate objects with additional metadata.
    Homogeneous Data Types:- All elements in a NumPy array are of the same data type, which allows for more compact storage and faster access. In contrast, Python lists can store elements of different types, leading to increased memory usage.
    * Performance > 
    Vectorized Operations:- NumPy supports vectorized operations, which means that operations are applied element-wise across the entire array without the need for explicit loops. This is much faster than iterating through elements in a Python list.
    Implementation in C:- NumPy is implemented in C, which is a lower-level language than Python. This allows NumPy to leverage highly optimized C libraries for numerical computations, resulting in significant speed improvements.
    * Broadcasting >
    Automatic Dimension Expansion:- NumPy’s broadcasting feature allows arrays of different shapes to be combined in arithmetic operations. This eliminates the need for manual dimension alignment and makes operations more efficient.
    * Advanced Mathematical Functions >
    Rich Set of Functions:- NumPy provides a wide range of mathematical and statistical functions that are optimized for performance. These functions are not available in standard Python lists and would require additional libraries or custom implementations.
    * Ease of Use >
    Concise Syntax:- NumPy’s syntax for operations is more concise and closer to mathematical notation. For example, multiplying every element by a scalar is straightforward with NumPy arrays, whereas with lists, it would require a loop or a list comprehension.

# 07. Compare vstack() and hstack() functions in NumP. Provide examples demonstrating their usage and output.

Answer - 
   
   The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively.

   * vstack() >>  its purpose is to Stacks arrays in sequence vertically (row-wise); meaning it concatenates them along the first axis (rows).
   Useful when you want to add rows to an existing array.

   * hstack() >> Stacks arrays in sequence horizontally (column-wise).
    Useful when you want to add columns to an existing array.


    Key Differences:-

    vstack() combines arrays vertically, resulting in a new array with the same number of columns as the original arrays but with more rows.
    hstack() combines arrays horizontally, resulting in a new array with the same number of rows as the original arrays but with more columns.

    Both functions require the arrays to have compatible shapes. For vstack(), the arrays must have the same number of columns. For hstack(), the arrays must have the same number of rows.
    Can stack multiple arrays using these functions by providing them as a tuple or list to the function.

In [2]:
#example -

import numpy as np

# Creating two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

    # Stacking them vertically
result = np.vstack((a, b))
print(result)  


import numpy as np

    # Creating two 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

    # Stacking them vertically
result = np.vstack((a, b))
print(result)



#example-

import numpy as np

# Creating two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking them horizontally
result = np.hstack((a, b))
print(result)


import numpy as np

# Creating two 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

# Stacking them horizontally
result = np.hstack((a, b))
print(result)



[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# 08. Explain the difference between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Answer - 

    The fliplr() and flipud() methods in NumPy are used to flip arrays along different axes.

    fliplr() >> 

    Purpose:- Flips the array in the left/right direction(horizontally).
    Axis:- Operates along axis 1(columns).
    Effect:- Reverse the order of columns while keeping the rows intact.

    flipud() >> 

    Purpose:- Flips the array in the up/down direction(vertically).
    Axis:- Operates along axis 0 (rows).
    Effect:- Reverses the order of rows while keeping the columns intact.


### Effects on various array dimensions >> 

    1D Arrays :- fliplr() is not applicable to 1D arrays as it requires at least 2D arrays, but flipud() can be used to reverse a 1D array.
    2D Arrays :- both fliplr() and flipud() can be used, with fliplr() reversing columns and flipud() reversing rows.
    Higher-Dimensional Arrays :- both functions can be applied, but their effects will be more complex, involving the specified axes.

### These methods are useful for various data manipulation tasks, such as image processing, where flipping images horizontally or vertically is a common operation.


# 09. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Answer - 

    The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is particularly useful when you need to divide an array into parts that may not be of equal size.

    Functionality of array_split() >> 

    The array_split() method splits an array into multiple sub-arrays along a specified axis. The primary difference between array_split() and split() is that array_split() can handle cases where the array cannot be evenly divided by the specified number of splits.

    Syntax -> numpy.array_split(ary, indices_or_sections, axis=0)
    ary: the input array to be split.
    indices_or_sections: If an integer, it specifies the number of equal or nearly equal sub-arrays to create. If a 1-D array of sorted integers, it specifies the indices at which to split the array.
    axis: this axis along which to split the array. Default is 0(along rows).

    Handling Uneven Splits >>
    When the array cannot be evenly divided, array_split() ensures that the sub-arrays are as equal in size as possible. It distributes the remainder elements across the sub-arrays.

    Key points >>
    Flexibility: array_split() can handle both even and uneven splits, making it more versatile than split(), which requires equal division.

    Axis Specification : can specify the axis along which to split the array, allowing for flexible data manipulation.

    Automatic Distribution : When the array length is not perfectly divisible by the number of splits, array_split() distributes the remainder elements across the sub-arrays to ensure they are as equal in size as possible.

    These features make array_split() a powerful tool for dividing arrays into manageable parts, especially when dealing with datasets that do not neatly divide into equal sections.

# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Answer - 

    Vectorization:- refers to the process of performing operations on entire arrays rather than individual elements. This eliminates the need for explicit loops in Python, making the code more concise and significantly faster. NumPy achieves vectorization by leveraging highly optimized C and Fortran libraries under the hood.

    Broadcasting:- describes how NumPy handles arrays with different shapes during arithmetic operations. Smaller arrays are “broadcast” across larger arrays so that they have compatible shapes. This allows for efficient computation without the need for making copies of data.

    Broadcasting Rules:-
    If the arrays do not have the same rank, prepend the shape of the smaller array with ones until both shapes have the same length.
    The sizes of the arrays must match or one of them must be 1 in each dimension.

    Contributions to Efficient Array Operations >>

    * Performance:-
    Vectorization: By eliminating explicit loops, vectorization reduces the overhead of Python’s interpreted loops, leading to faster execution times.
    Broadcasting: Allows operations on arrays of different shapes without the need for reshaping or copying data, thus saving memory and computational resources.
    * Memory Efficiency:-
    Vectorization: Operates on entire arrays at once, reducing the need for intermediate storage and minimizing memory usage.
    Broadcasting: Avoids unnecessary data replication by conceptually expanding arrays without physically copying data.
    * Code Simplicity:-
    Vectorization: Makes the code more readable and concise by replacing loops with array operations.
    Broadcasting: Simplifies the code by allowing operations on arrays of different shapes without explicit reshaping.

    These features make NumPy a powerful tool for numerical and scientific computing, enabling efficient and scalable array operations.