### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

Answer ->

In [38]:
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchanging rows and columns
transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)

Original Array:
[[13 36 45]
 [47 88 74]
 [51 53 47]]

Transposed Array:
[[13 47 51]
 [36 88 53]
 [45 74 47]]


### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

Answer -

In [3]:
import numpy as np

# 1D array with 10 elements
arr = np.arange(10)
print("Original 1D Array:")
print(arr)

# Reshaping the array into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(arr_2x5)

# Reshaping the 2x5 array into a 5x2 array
arr_5x2 = arr_2x5.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(arr_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### 3. Create a 4x4 NumPy array with random float values. Add a border of zeroes around it, resulting in a 6x6 array.

In [4]:
import numpy as np

# 4x4 array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr)

# Adding border of zeroes around the array
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nArray with Border of Zeroes (6x6):")
print(arr_with_border)


Original 4x4 Array:
[[0.48632726 0.06712251 0.03950201 0.69318997]
 [0.81989037 0.63568431 0.49643752 0.03812729]
 [0.76249987 0.92571823 0.92165107 0.38428213]
 [0.94737401 0.67781624 0.49161027 0.18378817]]

Array with Border of Zeroes (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.48632726 0.06712251 0.03950201 0.69318997 0.        ]
 [0.         0.81989037 0.63568431 0.49643752 0.03812729 0.        ]
 [0.         0.76249987 0.92571823 0.92165107 0.38428213 0.        ]
 [0.         0.94737401 0.67781624 0.49161027 0.18378817 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

Answer -

In [5]:
import numpy as np

''' np.arange(start, stop, step) generates values starting from start up to
(but not including) stop, with a specified step.
In this case, np.arange(10, 65, 5) creates an array starting at 10,
ending before 65, with increments of 5.'''

arr = np.arange(10, 65, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


### 5. Create a NumPy array of strings['python','numpy','pandas']. Apply different case transformations (uppercase,lowercase,title case, etc.) to each element.
Answer -

In [8]:
import numpy as np

# Creating a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])
print("Original Array:")
print(arr)

# Converting it to uppercase
upper_arr = np.char.upper(arr)
print("\nUppercase Array:")
print(upper_arr)

# Converting it to lowercase
lower_arr = np.char.lower(arr)
print("\nLowercase Array:")
print(lower_arr)

# Converting it to title case
title_arr = np.char.title(arr)
print("\nTitle Case Array:")
print(title_arr)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Title Case Array:
['Python' 'Numpy' 'Pandas']


In [37]:
import numpy as np

# Creating a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Applying different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.capitalize(array)

print("Original array:", array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title case:", titlecase_array)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

Answer -

In [11]:
import numpy as np

words = np.array(['python', 'numpy', 'pandas'])
print("Original Array:")
print(words)

# Inserting a space between each character
spaced_words = np.char.join(' ', words)
print("\nArray with Spaces Between Characters:")
print(spaced_words)


Original Array:
['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

Answer ->

In [12]:
import numpy as np

# Creating two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

addition = np.add(arr1, arr2)
print("\nElement-wise Addition:")
print(addition)

subtraction = np.subtract(arr1, arr2)
print("\nElement-wise Subtraction:")
print(subtraction)

multiplication = np.multiply(arr1, arr2)
print("\nElement-wise Multiplication:")
print(multiplication)

division = np.divide(arr1, arr2)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

Answer ->

In [14]:
import numpy as np

"""the np.identity(5) function creates a 5x5 identity matrix, 
and the np.diag(identity_matrix)function extracts the diagonal elements,
which are all ones"""

identity_matrix = np.identity(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extracting the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

Answer ->

In [30]:
import numpy as np


random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers Array:")
print(random_integers)

#a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = np.array([num for num in random_integers if is_prime(num)])
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[ 146  481  575  822  474   59  354  422  622  916  253  830  253   58
    1  160  190  749  793  135  996  226  577  340  668  946  420  842
  642   55  198  583  775  690  381  916  383  271  428  302  535  287
  780  530  808  523   34  432  789  996  367  561  487  381  738  706
  649  303  209  778  107  854  676  146  513  744  626  350  527  678
  159  427  460  983  806  957  960  170  399  262  531  527  947  963
  412  700  193  112  872  983  419  747  900  693  945 1000  913  740
  343  554]

Prime Numbers in the Array:
[ 59 577 383 271 523 367 487 107 983 947 193 983 419]


### 10. Create a NumPy array representing daily temperature for a month. Calculate and display the weekly averages. 

Answer ->

In [36]:
import numpy as np

""" the daily temperatures are generated randomly between 20°C and 35°C.
The array is then reshaped to represent 4 weeks and the average 
temperature for each week is calculated and displayed"""

daily_temperatures = np.random.randint(20, 36, size=30)
print("Daily Temperatures for a Month:")
print(daily_temperatures)

# Reshaping the array to have 4 weeks (each with 7 days)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculating the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for a Month:
[28 20 29 20 23 20 23 32 32 20 29 21 22 32 30 28 23 22 30 30 21 31 29 29
 27 21 24 30 25 32]

Weekly Averages:
[23.28571429 26.85714286 26.28571429 27.28571429]
